name: "Validate Conformance Test Syntax"

on:
  push:
  pull_request:

jobs:
  check-conformance-test-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ion CLI
        run: cargo install ion-cli@0.11.0
      - name: Run validation script
        run: ./check-syntax
